# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Ubuntu Master
   config.vm.define "master" do |master|
     master.vm.box = "ubuntu/focal64"
     master.vm.hostname = "master"
     master.vm.network :private_network, ip: "192.168.60.4"
   end

 
   # Ubuntu Slave
   config.vm.define "slave" do |slave|
     slave.vm.box = "ubuntu/focal64"
     slave.vm.hostname = "slave"
     slave.vm.network :private_network, ip: "192.168.60.5"
   end
	
   config.vm.provider "virtualbox" do |vb|
	vb.gui = false
	vb.memory = 1024
	vb.cpus = 2
   end
 
 end